import { YukigoPrimitive } from "yukigo-core";

export const keywords = [
  "type",
  "where",
  "in",
  "if",
  "else",
  "then",
  "data",
  "case",
  "class",
  "do",
  "default",
  "deriving",
  "import",
  "infix",
  "infixl",
  "infixr",
  "instance",
  "let",
  "module",
  "newtype",
  "of",
  "qualified",
  "as",
  "hiding",
  "foreign",
];

export const typeMappings: { [key: string]: YukigoPrimitive } = {
  Float: "YuNumber",
  Double: "YuNumber",
  Int: "YuNumber",
  Integer: "YuNumber",
  String: "YuString",
  Char: "YuChar",
  Boolean: "YuBoolean",
  Bool: "YuBoolean",
};

export const typeClasses: Map<string, string[]> = new Map([
  ["Bounded", []],
  ["Enum", []],
  ["Ord", ["YuNumber", "YuString", "YuChar"]],
  ["Eq", ["YuNumber", "YuString", "YuChar", "YuBoolean"]],
  ["Floating", []],
  ["Fractional", []],
  ["Functor", []],
  ["Integral", []],
  ["Ix", []],
  ["Monad", []],
  ["MonadPlus", []],
  ["Num", ["YuNumber"]],
  ["Random", []],
  ["RandomGen", []],
  ["Read", []],
  ["Real", []],
  ["RealFloat", []],
  ["RealFrac", []],
  ["Show", []],
]);
